services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.9.3-python3.11
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: "requests python-dotenv pendulum"
    user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"
    command: >
      bash -c "pip install --no-cache-dir ${_PIP_ADDITIONAL_REQUIREMENTS} && airflow db init"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./.env:/opt/airflow/.env
      - ./logs:/opt/airflow/logs

  webserver:
    image: apache/airflow:2.9.3-python3.11
    depends_on:
      - airflow-init
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
      AIRFLOW__WEBSERVER__AUTH_BACKEND: airflow.www.fab_security.manager.AUTH_DB
      AIRFLOW__WEBSERVER__SECRET_KEY: this-is-a-long-random-secret-change-me
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: "requests python-dotenv pendulum"
    user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"
    command: webserver
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./.env:/opt/airflow/.env
      - ./logs:/opt/airflow/logs

  scheduler:
    image: apache/airflow:2.9.3-python3.11
    depends_on:
      - webserver
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: "requests python-dotenv pendulum"
    user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./.env:/opt/airflow/.env
      - ./logs:/opt/airflow/logs

volumes:
  pgdata: {}
